CREATE TABLE IF NOT EXISTS speedtest (
    'id' INTEGER PRIMARY KEY,
    'bytes_received' INTEGER,
    'bytes_sent' INTEGER,
    'client_country' TEXT,
    'client_ip' TEXT,
    'client_isp' TEXT,
    'client_ispdlavg' TEXT,
    'client_isprating' TEXT,
    'client_ispulavg' TEXT,
    'client_lat' TEXT,
    'client_loggedin' TEXT,
    'client_lon' TEXT,
    'client_rating' TEXT,
    'download' REAL,
    'ping' REAL,
    'server_cc' TEXT,
    'server_country' TEXT,
    'server_d' REAL,
    'server_host' TEXT,
    'server_id' TEXT,
    'server_lat' TEXT,
    'server_latency' REAL,
    'server_lon' TEXT,
    'server_name' TEXT,
    'server_sponsor' TEXT,
    'server_url' TEXT,
    'share' TEXT,
    'timestamp' TEXT,
    'upload' REAL
);